//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolLed_XuanCuong.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAutoStart {
            get {
                return ((bool)(this["isAutoStart"]));
            }
            set {
                this["isAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_stt_top_ID {
            get {
                return ((string)(this["led_stt_top_ID"]));
            }
            set {
                this["led_stt_top_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_stt_bottom_ID {
            get {
                return ((string)(this["led_stt_bottom_ID"]));
            }
            set {
                this["led_stt_bottom_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_service_code_top_ID {
            get {
                return ((string)(this["led_service_code_top_ID"]));
            }
            set {
                this["led_service_code_top_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_service_code_bottom_ID {
            get {
                return ((string)(this["led_service_code_bottom_ID"]));
            }
            set {
                this["led_service_code_bottom_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_china_plate_code_top_ID {
            get {
                return ((string)(this["led_china_plate_code_top_ID"]));
            }
            set {
                this["led_china_plate_code_top_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_china_plate_code_bottom_ID {
            get {
                return ((string)(this["led_china_plate_code_bottom_ID"]));
            }
            set {
                this["led_china_plate_code_bottom_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_VN_plate_code_top_ID {
            get {
                return ((string)(this["led_VN_plate_code_top_ID"]));
            }
            set {
                this["led_VN_plate_code_top_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_VN_plate_code_bottom_ID {
            get {
                return ((string)(this["led_VN_plate_code_bottom_ID"]));
            }
            set {
                this["led_VN_plate_code_bottom_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_position_code_top_ID {
            get {
                return ((string)(this["led_position_code_top_ID"]));
            }
            set {
                this["led_position_code_top_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_position_code_bottom_ID {
            get {
                return ((string)(this["led_position_code_bottom_ID"]));
            }
            set {
                this["led_position_code_bottom_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_group_top_ID {
            get {
                return ((string)(this["led_group_top_ID"]));
            }
            set {
                this["led_group_top_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_group_bottom_ID {
            get {
                return ((string)(this["led_group_bottom_ID"]));
            }
            set {
                this["led_group_bottom_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_status_top_ID {
            get {
                return ((string)(this["led_status_top_ID"]));
            }
            set {
                this["led_status_top_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string led_status_bottom_ID {
            get {
                return ((string)(this["led_status_bottom_ID"]));
            }
            set {
                this["led_status_bottom_ID"] = value;
            }
        }
    }
}
